FROM python:3.7-slim

WORKDIR /usr/src/fulhaus

COPY requirements.txt ./

RUN pip install -r requirements.txt \
    && rm -rf /root/.cache/pip

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

COPY . .

ENTRYPOINT ["python", "app.py"]